on: push
name: dotnet-ci

permissions:
  contents: read

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
          dotnet-quality: 'preview'
      - name: Restore
        working-directory: ./code/
        run: dotnet restore
  build:
    needs: restore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
          dotnet-quality: 'preview'
      - name: Build
        working-directory: ./code/
        run: dotnet build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
          dotnet-quality: 'preview'
      - name: Test
        working-directory: ./code/
        run: dotnet test --filter "Category!=Performance" --verbosity normal
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
          dotnet-quality: 'preview'
      - name: Pack and validate compatibility
        run: dotnet pack code/Universe/UniverseQuery.csproj -c Release
